# Завдання 1 
Звантажити та відкрити (вручну або через запропонований скрипт на сайті) наступний датасет: Individual Household Electric Power Consumption Dataset

In [1]:
import pandas as pd
import numpy as np
import timeit
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:

def load_initial_data(file_path):
    df = pd.read_csv(file_path, sep=';', low_memory=False, na_values=['?'])
    return df

file_name = 'household_power_consumption.txt'
df = load_initial_data(file_name)

print(f"Кількість рядків до очищення: {len(df)}")

print("Перші 5 рядків датасету:")
df.head()

Кількість рядків до очищення: 2075259
Перші 5 рядків датасету:

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

# Завдання 2
Здійснити data cleaning

In [3]:
def clean_power_data(df):
    df_cleaned = df.dropna().copy()
    

    float_cols = df_cleaned.columns[2:] 
    for col in float_cols:
        df_cleaned[col] = pd.to_numeric(df_cleaned[col])
        
    df_cleaned['DateTime'] = pd.to_datetime(df_cleaned['Date'] + ' ' + df_cleaned['Time'], dayfirst=True)
    
    return df_cleaned

print(f"Кількість рядків після очищення: {len(df)}")

Кількість рядків після очищення: 2075259

# Завдання 3
## Окремими функціями сформувати вибірки:

**Обрати всі записи, у яких загальна активна споживана потужність перевищує 5 кВт**

In [4]:
def filter_by_active_power(df):
    return df[df['Global_active_power'] > 5.0]

execution_time = timeit.timeit(lambda: filter_by_active_power(df), number=1)

result_power = filter_by_active_power(df)

print(f"Завдання виконано за: {execution_time:.6f} секунд")
print(f"Кількість знайдених записів: {len(result_power)}")

result_power.head()

Завдання виконано за: 0.009548 секунд
Кількість знайдених записів: 17547

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
11,16/12/2006,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0
12,16/12/2006,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0

**Обрати всі записи, у яких сила струму лежить в межах 19-20 А, для них виявити ті, у яких пральна машина та холодильних споживають більше, ніж бойлер та кондиціонер**

In [5]:
def filter_by_intensity_and_consumption(df):
    
    return df[(df['Global_intensity'] >= 19) & 
              (df['Global_intensity'] <= 20) & 
              (df['Sub_metering_2'] > df['Sub_metering_3'])]

execution_time = timeit.timeit(lambda: filter_by_intensity_and_consumption(df), number=1)

result_intensity = filter_by_intensity_and_consumption(df)

print(f"Завдання виконано за: {execution_time:.6f} секунд")
print(f"Кількість знайдених записів: {len(result_intensity)}")

result_intensity.head()

Завдання виконано за: 0.024891 секунд
Кількість знайдених записів: 2509

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
45,16/12/2006,18:09:00,4.464,0.136,234.66,19.0,0.0,37.0,16.0
460,17/12/2006,01:04:00,4.582,0.258,238.08,19.6,0.0,13.0,0.0
464,17/12/2006,01:08:00,4.618,0.104,239.61,19.6,0.0,27.0,0.0
475,17/12/2006,01:19:00,4.636,0.140,237.37,19.4,0.0,36.0,0.0
476,17/12/2006,01:20:00,4.634,0.152,237.17,19.4,0.0,35.0,0.0

**Обрати випадковим чином 500000 записів (без повторів елементів вибірки), для них обчислити середні величини усіх 3-х груп споживання електричної енергії**

In [6]:
def get_random_sample_stats(df, n_samples=500000):
    
    sample_df = df.sample(n=n_samples, replace=False)
    
    means = sample_df[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']].mean()
    
    return means

execution_time = timeit.timeit(lambda: get_random_sample_stats(df), number=1)
result_means = get_random_sample_stats(df)

print(f"Завдання виконано за: {execution_time:.6f} секунд")
print("\nСередні величини споживання для 500 000 випадкових записів:")
print(result_means)

Завдання виконано за: 0.394858 секунд

Середні величини споживання для 500 000 випадкових записів:
Sub_metering_1    1.111556
Sub_metering_2    1.292364
Sub_metering_3    6.463710
dtype: float64

**Обрати ті записи, які після 18-00 споживають понад 6 кВт за хвилину в середньому, серед відібраних визначити ті, у яких основне споживання електроенергії у вказаний проміжок часу припадає на пральну машину, сушарку, холодильник та освітлення (група 2 є найбільшою), а потім обрати кожен третій результат із першої половини та кожен четвертий результат із другої половини**

In [7]:
def final_complex_filter(df):
    initial_filter = df[(df['Time'] > '18:00:00') & 
                        (df['Global_active_power'] > 6.0)].copy()
    
    mask_group2 = (initial_filter['Sub_metering_2'] > initial_filter['Sub_metering_1']) & \
                  (initial_filter['Sub_metering_2'] > initial_filter['Sub_metering_3'])
    
    res = initial_filter[mask_group2]
    
    n = len(res)
    if n == 0: return "Результатів не знайдено"
    
    half = n // 2
    first_part = res.iloc[:half:3]
    second_part = res.iloc[half::4]
    
    return pd.concat([first_part, second_part])

execution_time = timeit.timeit(lambda: final_complex_filter(df), number=1)
result = final_complex_filter(df)

print(f"Завдання виконано за: {execution_time:.6f} секунд")
print(f"Кількість результатів: {len(result)}")
result.head()

Завдання виконано за: 0.308917 секунд
Кількість результатів: 310

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
41,16/12/2006,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0
44,16/12/2006,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0
17494,28/12/2006,20:58:00,6.386,0.374,236.63,27.0,1.0,36.0,17.0
17498,28/12/2006,21:02:00,8.088,0.262,235.50,34.4,1.0,72.0,17.0
17501,28/12/2006,21:05:00,7.230,0.152,235.22,30.6,1.0,73.0,17.0

# Завдання 4
Пронормувати та стандартизувати вибраний датасет

In [8]:
def apply_scaling(df):
    columns_to_scale = [
        'Global_active_power', 'Global_intensity', 
        'Voltage', 'Sub_metering_1', 
        'Sub_metering_2', 'Sub_metering_3'
    ]
    data = df[columns_to_scale]
    
    scaler_minmax = MinMaxScaler()
    normalized_array = scaler_minmax.fit_transform(data)
    
    df_norm = pd.DataFrame(normalized_array, columns=columns_to_scale)

    scaler_std = StandardScaler()
    standardized_array = scaler_std.fit_transform(data)
    df_std = pd.DataFrame(standardized_array, columns=columns_to_scale)

    return df_norm, df_std

norm_results, std_results = apply_scaling(df)

print("Приклад нормалізованих даних (діапазон 0-1):")
display(norm_results.head(3))

print("\nПриклад стандартизованих даних (середнє 0, відхилення 1):")
display(std_results.head(3))

Приклад нормалізованих даних (діапазон 0-1):

,Global_active_power,Global_intensity,Voltage,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,0.374796,0.377593,0.376090,0.0,0.0125,0.548387
1,0.478363,0.473029,0.336995,0.0,0.0125,0.516129
2,0.479631,0.473029,0.326010,0.0,0.0250,0.548387

Приклад стандартизованих даних (середнє 0, відхилення 1):

,Global_active_power,Global_intensity,Voltage,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2.955077,3.098789,-1.851816,-0.182337,-0.051274,1.249421
1,4.037085,4.133800,-2.225274,-0.182337,-0.051274,1.130897
2,4.050326,4.133800,-2.330213,-0.182337,0.120487,1.249421

# Завдання 5
Підрахувати коефіцієнт Пірсона та Спірмена для двох integer/real атрибутів

In [9]:
def analyze_correlation(df, col1, col2):
    pearson = df[col1].corr(df[col2], method='pearson')
    spearman = df[col1].corr(df[col2], method='spearman')
    
    return pearson, spearman

attr1 = 'Global_active_power'
attr2 = 'Global_intensity'

p_corr, s_corr = analyze_correlation(df, attr1, attr2)

print(f"Коефіцієнт Пірсона: {p_corr:.5f}")
print(f"Коефіцієнт Спірмена: {s_corr:.5f}")

Коефіцієнт Пірсона: 0.99889
Коефіцієнт Спірмена: 0.99537

# Завдання 6
Провести One Hot Encoding категоріального атрибута

In [10]:
def add_weekend_category(df):
    temp_date = pd.to_datetime(df['Date'], dayfirst=True)
    
    df_cat = df.copy()
    df_cat['Day_Type'] = np.where(temp_date.dt.weekday >= 5, 'Weekend', 'Weekday')
    
    ohe_days = pd.get_dummies(df_cat[['Date', 'Day_Type', 'Global_active_power']].head(1000), 
                              columns=['Day_Type'], 
                              prefix='Is')
    
    return ohe_days

weekend_ohe = add_weekend_category(df)

display(weekend_ohe.head(10))

         Date  Global_active_power  Is_Weekend
0  16/12/2006                4.216        True
1  16/12/2006                5.360        True
2  16/12/2006                5.374        True
3  16/12/2006                5.388        True
4  16/12/2006                3.666        True
5  16/12/2006                3.520        True
6  16/12/2006                3.702        True
7  16/12/2006                3.700        True
8  16/12/2006                3.668        True
9  16/12/2006                3.662        True